#!/bin/bash
#-----------------------------------------------------------------------
# Copyright (c) 2017, Jeff Layton <jlayton@redhat.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------

_wb_fault_set()
{
	ls /sys/kernel/debug/ceph/*/wb_fault |
	while read file; do
		echo "$1" > $file
	done
}

case $1 in
cleanup)
	_wb_fault_set 0
	;;
init)
	_wb_fault_set 0
	;;
load_error_table)
	_wb_fault_set 1
	;;
load_working_table)
	_wb_fault_set 0
	;;
*)
	echo "Usage: $0 {init|cleanup|load_error_table|load_working_table}"
	exit 1
	;;
esac

status=0
exit
